### ISSUE TITLE
JWT token integration in Frontend

### ISSUE THREAD

**Issue by antwan38** [Fontys-Refactoring-Flow/Refactoring-Flow-Frontend#1]
In de backend is JWT(JSON webtokens) geïmplementeerd, in de front-end nog niet. Om de veiligheid van de applicatie te verbeteren zal dit geïmplementeerd moeten worden.

**Comment by IemandDieAbeHeet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [JWT(JSON webtokens) implementeren in de front-end](https://trello.com/c/wdRrgZLT/18-jwtjson-webtokens-implementeren-in-de-front-end)
